#!/bin/bash

#
#  db_backup
#
#  Copyright 2012 Miguel Sánchez de León Peque <msdeleonpeque@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

MYSQL_USER="user"
MYSQL_DB="database"
MYSQL_PASS="password"

FTP_SERVER="host_name"
FTP_USER="user_name"
FTP_PASS="password"

MYSQL_BACKUP_FILE=${MYSQL_DB}_$(date -Ins).sql.gz

mysqldump -u $MYSQL_USER -p$MYSQL_PASS $MYSQL_DB | gzip > /tmp/$MYSQL_BACKUP_FILE

ftp -inv $FTP_SERVER << EOF
user $FTP_USER $FTP_PASS
put /tmp/$MYSQL_BACKUP_FILE $MYSQL_BACKUP_FILE
bye
EOF

rm /tmp/$MYSQL_BACKUP_FILE
