#!/bin/bash

#
#  update_all_users_permissions
#
#  Copyright 2012 Miguel Sánchez de León Peque <msdeleonpeque@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

MYSQL_USER=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_user | tr "\t" "_" | tr "'" "\t" | cut -f2)
MYSQL_DB=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_name | tr "\t" "_" | tr "'" "\t" | cut -f2)
MYSQL_PASS=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_pass | tr "\t" "_" | tr "'" "\t" | cut -f2)

permission="student"
value="1"

users=$(mysql -h localhost -u $MYSQL_USER -p$MYSQL_PASS -D $MYSQL_DB -s -e "select number from users;")

for number in $users; do
	mysql -h localhost -u $MYSQL_USER -p$MYSQL_PASS -D $MYSQL_DB -s -e "insert into permissions (user,$permission) values ($number,$value) on duplicate key update $permission=values($permission);"
done
