#!/bin/bash

#
#  users2db
#
#  Copyright 2012 Miguel Sánchez de León Peque <msdeleonpeque@gmail.com>
#
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 3 of the License, or
#  (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#

MYSQL_USER=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_user | tr "\t" "_" | tr "'" "\t" | cut -f2)
MYSQL_DB=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_name | tr "\t" "_" | tr "'" "\t" | cut -f2)
MYSQL_PASS=$(cat $(dirname ${BASH_SOURCE[0]})/../config.php | grep -e db_pass | tr "\t" "_" | tr "'" "\t" | cut -f2)

while read pipe_line; do

	reg_num=$(echo $pipe_line | awk '{ print $1 }')
	pass=$(echo $pipe_line | awk '{ print $2 }')

	mysql -h localhost -u $MYSQL_USER -p$MYSQL_PASS -D $MYSQL_DB -s -e "insert ignore into users (id,password) values ('$reg_num','$pass');"

done
